/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BLL.CourseBLL;
import BLL.CourseInstructorBLL;
import DAL.entities.CourseInstructor;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Tính
 */
public class Statistic_Instructor extends javax.swing.JFrame implements ActionListener {

    private final CourseInstructorBLL ciBLL = new CourseInstructorBLL();
    private final CourseBLL cBLL = new CourseBLL();
    private List<CourseInstructor> list;
    private final int totalCourse = cBLL.getAllCourse().size();

    /**
     * Creates new form AddStudentGrade
     */
    public Statistic_Instructor() {
        initComponents();
        fillInstructor();
        Chart_Panel2.setBackground(Color.red);
        Instructor_Cbb.addActionListener(this);

        list = ciBLL.getCoursesByPersonID(getNameFromString((String) Instructor_Cbb.getSelectedItem()));

        showBarChart(list);

        pack();
        setLocationRelativeTo(null);
    }

    private void showBarChart(List<CourseInstructor> list) {
        DefaultPieDataset pieChartData = new DefaultPieDataset();

        int count = 0;
        for (CourseInstructor stt : list) {
            pieChartData.setValue(stt.getTitle(), 1);
            System.out.println(stt.toString());
            count++;
        }

        pieChartData.setValue("Others", totalCourse - count);

        JFreeChart pieChart = ChartFactory.createPieChart3D("Khoá học " + getNameFromString2((String) Instructor_Cbb.getSelectedItem()) + " tham gia giảng dạy ", pieChartData, true, true, false);

        PiePlot pieP = (PiePlot) pieChart.getPlot();
        pieP.setSectionPaint("Others", Color.LIGHT_GRAY);
        pieP.setBackgroundPaint(Color.WHITE);
        ChartPanel piePanel = new ChartPanel(pieChart);
        piePanel.setPreferredSize(new Dimension(576, 356));

        Chart_Panel2.removeAll();
        Chart_Panel2.setLayout(new BorderLayout());

        Chart_Panel2.add(piePanel, BorderLayout.CENTER);

        Chart_Panel2.revalidate();

        repaint();

        jLabel3.setText(list.size() + "/" + totalCourse);

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        list = ciBLL.getCoursesByPersonID(getNameFromString((String) Instructor_Cbb.getSelectedItem()));
        showBarChart(list);
    }

    private String getNameFromString2(String nameID) {
        String[] parts = nameID.split("- ID:");
        //System.out.println("Debug - nameID: " + nameID); // Thêm dòng này để xem giá trị của nameID

        if (parts.length == 2) {
            try {
                return parts[0].trim();
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        }
        return null;
    }

    private int getNameFromString(String nameID) {
        String[] parts = nameID.split("- ID:");
        //System.out.println("Debug - nameID: " + nameID); // Thêm dòng này để xem giá trị của nameID

        if (parts.length == 2) {
            try {
                return Integer.parseInt(parts[1].trim());
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        }
        return -1;
    }

    private void fillInstructor() {
        List<CourseInstructor> listCi = ciBLL.getAllCourseInstructor();
        Instructor_Cbb.removeAllItems();
        for (CourseInstructor ps : listCi) {
            Instructor_Cbb.addItem(ps.getInstructor().getLastname() + " " + ps.getInstructor().getFirstname() + " - ID: " + ps.getInstructor().getPersonID());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Instructor_Cbb = new javax.swing.JComboBox<>();
        Chart_Panel2 = new javax.swing.JPanel(new BorderLayout());
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 300));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê phân công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 13), new java.awt.Color(204, 0, 51))); // NOI18N

        jLabel1.setText("Instructor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Instructor_Cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Instructor_Cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Chart_Panel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Chart_Panel2Layout = new javax.swing.GroupLayout(Chart_Panel2);
        Chart_Panel2.setLayout(Chart_Panel2Layout);
        Chart_Panel2Layout.setHorizontalGroup(
            Chart_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        Chart_Panel2Layout.setVerticalGroup(
            Chart_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jLabel2.setText("Tổng số khoá học đang dạy:");

        jLabel3.setText("x/x");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Chart_Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Chart_Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Chart_Panel2;
    private javax.swing.JComboBox<String> Instructor_Cbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
